### ISSUE TITLE
move all content to this repository?

### ISSUE THREAD

**Issue by fmichonneau** [carpentries-incubator/life-sciences-workshop#1]
hi @RobHarrand,

thanks for transferring your lesson to the Carpentries Incubator!

It looks like this repository is used a pointer to other lessons. I'm wondering if it would make sense to move the lessons you link to in this lesson directly in this repository and include in the index page how the episodes are intended to be distributed over the 2 days of the content you developed?

Let us  know what you think!

**Comment by RobHarrand** [comment]
Hi @fmichonneau 

That makes a lot more sense! I've now moved everything to this repo.

**Comment by RobHarrand** [comment]
Hi @fmichonneau @ErinBecker what's next on this? Please let me know if I need to do something. Thanks.

**Comment by fmichonneau** [comment]
hi @RobHarrand, we'll follow up in the next few days/weeks. We are currently focusing most of our efforts to respond to the consequences of the COVID-19 pandemic on our community and our operations. Thanks for your understanding.

**Comment by RobHarrand** [comment]
Hi @fmichonneau , of course, I totally understand. All the best. Thanks.

**Comment by RobHarrand** [comment]
Hi @fmichonneau ... whilst the DC team are busy with COVID-19, is there anything I could do on this? I'm planning a 'pre-alpha' workshop soon, so I'll be updating the material. What happens next with the repo? Thanks.

**Comment by fmichonneau** [comment]
thank you for your patience and thank you for transferring all the episodes in this repo.
I'm going through your lesson and I'll open a few issues around technical things to make sure your lesson plays nicely with the template.
