### ISSUE TITLE
update links to episodes

### ISSUE THREAD

**Issue by fmichonneau** [carpentries-incubator/life-sciences-workshop#3]
in the index file, it looks like you replaced the default table with direct links to the github version of the episodes.

With the template, your lesson is currently rendered at https://carpentries-incubator.github.io/life-sciences-workshop/

Once the Rmarkdown files will be recognized by the template, the Rmd files will be knit into Markdown files in the `_episodes` folder and the default table that comes with the template will list all the episodes.

If you prefer to keep your customized version of the index file, you'll need to replace the links to: `{{ page.root }}{% link _episodes/01-project-organisation-introduction.md %}` for instance.

Tangentially related, for lessons that rely on Rmarkdown, I can set you up with Continuous Integration (we've been using Travis, but I'd like to start setting up new repositories with GitHub Actions) to render automatically the Rmd files into Markdown in the episodes folder so you don't have to render these files locally and keep both the md and the Rmd versions in the repository.

**Comment by RobHarrand** [comment]
Hi @fmichonneau I believe I've addressed the issues. I'm afraid I'm a bit of a Git novice. I merged your requests, and I've removed the hard-coded links in the index file. Please let me know if I've done anything crazy! Thanks.

**Comment by RobHarrand** [comment]
Hi @fmichonneau , just looking again, the Rmarkdown files don't seem to be recognised by the template. Is there something I need to do? Thanks.

**Comment by fmichonneau** [comment]
see #5 and let me know if this helps!

**Comment by RobHarrand** [comment]
Hi @fmichonneau . This is all sorted now and looking pretty good I think. Thanks for your help! I had a bit of trouble with the makefile but I've managed to run it now via Cygwin for Windows.
